language: julia
sudo: required
dist: trusty
julia:
  - 0.4
  - 0.5
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pdf2svg
  - sudo apt-get install -y texlive-latex-base
  - sudo apt-get install -y texlive-binaries
  - sudo apt-get install -y texlive-pictures
  - sudo apt-get install -y texlive-latex-extra
  - lualatex -v
after_success:
  - julia -e 'cd(Pkg.dir("TikzGraphs")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
